using ErpSaas.Shared.Data;
using ErpSaas.Shared.Services;

namespace ErpSaas.Modules.Crm.Entities;

[Auditable("Customer.Mutated")]
public class Customer : TenantEntity
{
    /// <summary>Unique code per shop — generated by CrmService (e.g. "CUST00001").</summary>
    public string CustomerCode { get; set; } = "";

    public string DisplayName { get; set; } = "";

    /// <summary>DDL key: CUSTOMER_TYPE. Values: Retail | Wholesale.</summary>
    public string CustomerType { get; set; } = "";

    public string? Email { get; set; }

    public string? Phone { get; set; }

    public string? GstNumber { get; set; }

    public decimal CreditLimitAmount { get; set; } = 0m;

    public decimal OutstandingAmount { get; set; } = 0m;

    public long? CustomerGroupId { get; set; }

    public bool IsActive { get; set; } = true;

    // Navigations
    public CustomerGroup? CustomerGroup { get; set; }
    public ICollection<CustomerAddress> Addresses { get; set; } = [];
}
