#!/usr/bin/env bash
# Run once to create all Azure staging resources.
# Prerequisites: az CLI installed and logged in (az login)
#
# Usage:
#   export SQL_ADMIN_PASSWORD="YourStrong@Passw0rd99"
#   bash ops/azure/provision-staging.sh

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────
RESOURCE_GROUP="erp-saas-staging-rg"
LOCATION="centralindia"
APP_SERVICE_PLAN="erp-saas-staging-plan"
WEBAPP_NAME="erp-saas-api-staging"
STATIC_STAFF="erp-staff-staging"
STATIC_PORTAL="erp-portal-staging"
SQL_SERVER="erp-saas-staging-sql"
SQL_ADMIN_USER="erpadmin"
SQL_ADMIN_PASSWORD="${SQL_ADMIN_PASSWORD:?Set SQL_ADMIN_PASSWORD env var before running}"

echo "▶ Creating resource group..."
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none

echo "▶ Creating App Service Plan (Linux B1)..."
az appservice plan create \
  --name "$APP_SERVICE_PLAN" \
  --resource-group "$RESOURCE_GROUP" \
  --sku B1 \
  --is-linux \
  --output none

echo "▶ Creating API Web App (.NET 8)..."
az webapp create \
  --name "$WEBAPP_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --plan "$APP_SERVICE_PLAN" \
  --runtime "DOTNETCORE:8.0" \
  --output none

# Tell ASP.NET Core to use the Staging environment
az webapp config appsettings set \
  --name "$WEBAPP_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --settings ASPNETCORE_ENVIRONMENT=Staging \
  --output none

echo "▶ Creating SQL Server..."
az sql server create \
  --name "$SQL_SERVER" \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --admin-user "$SQL_ADMIN_USER" \
  --admin-password "$SQL_ADMIN_PASSWORD" \
  --output none

# Allow Azure services (App Service) to reach SQL
az sql server firewall-rule create \
  --resource-group "$RESOURCE_GROUP" \
  --server "$SQL_SERVER" \
  --name AllowAzureServices \
  --start-ip-address 0.0.0.0 \
  --end-ip-address 0.0.0.0 \
  --output none

echo "▶ Creating databases..."
for DB in PlatformDb TenantDb AnalyticsDb LogDb NotificationsDb; do
  echo "   $DB"
  az sql db create \
    --resource-group "$RESOURCE_GROUP" \
    --server "$SQL_SERVER" \
    --name "$DB" \
    --service-objective Basic \
    --output none
done

echo "▶ Setting connection strings on App Service..."
SQL_HOST="${SQL_SERVER}.database.windows.net"
CONN_BASE="Server=${SQL_HOST};User Id=${SQL_ADMIN_USER};Password=${SQL_ADMIN_PASSWORD};Encrypt=true;TrustServerCertificate=false;"

az webapp config connection-string set \
  --name "$WEBAPP_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --connection-string-type SQLServer \
  --settings \
    "PlatformDb=${CONN_BASE}Database=PlatformDb;" \
    "TenantDb=${CONN_BASE}Database=TenantDb;" \
    "AnalyticsDb=${CONN_BASE}Database=AnalyticsDb;" \
    "LogDb=${CONN_BASE}Database=LogDb;" \
    "NotificationsDb=${CONN_BASE}Database=NotificationsDb;" \
  --output none

echo "▶ Creating Static Web Apps (free tier)..."
# Static Web Apps are only available in a limited set of regions
az staticwebapp create \
  --name "$STATIC_STAFF" \
  --resource-group "$RESOURCE_GROUP" \
  --location "eastasia" \
  --output none

az staticwebapp create \
  --name "$STATIC_PORTAL" \
  --resource-group "$RESOURCE_GROUP" \
  --location "eastasia" \
  --output none

echo ""
echo "✅ Azure resources created."
echo ""
echo "══════════════════════════════════════════════════════════"
echo " NEXT STEPS — do these once in GitHub"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "1. Set JWT secret on App Service:"
echo "   az webapp config appsettings set \\"
echo "     --name $WEBAPP_NAME \\"
echo "     --resource-group $RESOURCE_GROUP \\"
echo "     --settings Jwt__Secret=<min-32-char-secret>"
echo ""
echo "2. Download API publish profile and add to GitHub:"
echo "   Azure Portal → $WEBAPP_NAME → Get publish profile"
echo "   GitHub → Settings → Secrets → New: AZURE_PUBLISH_PROFILE"
echo ""
echo "3. Get Static Web App tokens and add to GitHub:"
echo "   az staticwebapp secrets list --name $STATIC_STAFF --query 'properties.apiKey'"
echo "   → GitHub secret: AZURE_STATIC_WEB_APPS_TOKEN_STAFF"
echo ""
echo "   az staticwebapp secrets list --name $STATIC_PORTAL --query 'properties.apiKey'"
echo "   → GitHub secret: AZURE_STATIC_WEB_APPS_TOKEN_PORTAL"
echo ""
echo "4. Add GitHub environment variable:"
echo "   GitHub → Settings → Environments → staging → Variables"
echo "   AZURE_WEBAPP_NAME = $WEBAPP_NAME"
echo ""
echo "5. Push to main → CI passes → deploy-staging.yml fires automatically"
echo ""
echo "API URL:    https://${WEBAPP_NAME}.azurewebsites.net"
echo "Staff app:  https://<auto-generated>.azurestaticapps.net"
echo "Portal:     https://<auto-generated>.azurestaticapps.net"
